#!/bin/bash 
set -xe
docker-compose -f $1 exec zk1  /opt/kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 3 --partitions 3 --config min.insync.replicas=2  --topic testeperda 